### ISSUE TITLE
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :    line 2 did not have 4 elements

### ISSUE THREAD

**Issue by clarunger** [adrianclo/meaR#2]
Hey there! I've been trying to run your code to analyze some MEA data. It works perfectly with your sample data. However, when I try with my own, I get the following error message:
![image](https://github.com/user-attachments/assets/02079f42-8585-4425-b5b6-93e110b2fa35)

I tried adding one of your files as the first in the meaTable list, and it seems to actually process that, but then gives this error as soon as it comes to my own files. The structure does look really similar to your sample txt spike files though (see screenshot below). It has less entries maybe, but similar otherwise. What do you think is the reason for the error message? 

![image](https://github.com/user-attachments/assets/6d4ee545-5b07-4e3b-bc94-44674f3e8cac)

Thank you very much in advance and really looking forward to using your code with my data. 
Clara

**Comment by adrianclo** [comment]
Hi Clara. Thank you for reaching out! It seems your file and the demo files have a minor difference (tab indentation after "Frequency" that is absent in your file). I will update the compiler function this weekend.

**Comment by adrianclo** [comment]
updated!
