### ISSUE TITLE
Error in if (sum(ss_channel$isiThreshold == TRUE) == 0) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by clarunger** [adrianclo/meaR#3]
Hi Adrian!
Thanks again for solving the past issue so quickly! That part seems to be working now. 
However, I stumbled upon a different error message now, when it comes to the inter-spike intervals. 

This is the error message:
```
Error in if (sum(ss_channel$isiThreshold == TRUE) == 0) { : 
  missing value where TRUE/FALSE needed

```
As far as I understand, it doesn't seem to have put a boolean for isiThreshold. I was wondering whether this might be due to missing values for isi in the .txt files? I am uploading one example file here. 

Thank you very much again for your support!
Best, 
Clara

[slice 1 81024.txt](https://github.com/user-attachments/files/17294995/slice.1.81024.txt)

**Comment by adrianclo** [comment]
Hi Clara. Thanks for reaching out. I am trying to replicate it. Can you provide more information? What is the maxRecording? maxduration? lowerThreshold? 

using the default values, I get an empty data.frame at the end of the `active_filter()`

Also, for the next function, did you use the default values, or others?
(isi_threshold = 50, spikes_per_burst = 5)


Thanks!

**Comment by clarunger** [comment]
Thanks for the response!
Here is what the meaTable looks like:
![image](https://github.com/user-attachments/assets/da8cfabd-fea7-4ab6-9962-f245e4f5b9a6)

The maxduration is 300 and otherwise I proceeded with the default (lowerThreshold = .01, isi_threshold = 50, spikes_per_burst = 5). 

Thanks a lot again for looking into this!
Kindly,
Clara

**Comment by adrianclo** [comment]
Hi Clara. the isiThreshold issue has been solved. However, there still an issue. no bursts were identified in the first slice (given the default params). Is that possible? If yes. Then, I will have to adapt that this is a possibility. 


Thanks!
Cheers, Adrian

**Comment by clarunger** [comment]
Hey Adrian, 
Thanks again for the reply!
Yes, it would be amazing if you could adapt the code for this possibility. 
Cheers, 
Clara

**Comment by adrianclo** [comment]
Hi Clara. bug in burst identifier removed
